{{ config(materialized='table') }}

SELECT O_ORDERDATE, SUM(O_TOTALPRICE) AS TOTAL_PRICE,

SUM(TOTAL_PRICE) OVER (ORDER BY O_ORDERDATE

                     ROWS BETWEEN 1 PRECEDING AND CURRENT ROW)

           AS CUMULATIVE_SALES

FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."ORDERS"

GROUP BY O_ORDERDATE