
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: cumulative_orders_by_date
    description: "Calculate the cumulative sales for the order date"
    columns:
      - name: o_orderdate
        tests:
          - unique
          - not_null
  - name: incremental_time
  - name: playing_with_test
    description: "Play with tests"
    columns:
      - name: c_custkey
        tests:
          - unique
          - not_null
      - name: c_mktsegment
        tests:
          - accepted_values:
              values: ["BUILDING", "AUTOMOBILE", "MACHINERY", "HOUSEHOLD", "FURNITURE"]